### ISSUE TITLE
Issue with rust and rustboard widget

### ISSUE THREAD

**Issue by monybg** [brainfoolong/rcon-web-admin#18]
After Rust version 2052 the rustboard widget is frozen. It doesn't display the current players anymore and sometimes not even the server name/version. Everything else works fine. If i execute "status" in the console widget the output is correct. The error.log is flooded with this:

`http request callback error SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at /home/rust/rcon-web-admin/src/steamapi.js:37:33
    at IncomingMessage.<anonymous> (/home/rust/rcon-web-admin/src/request.js:34:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`

**Comment by brainfoolong** [comment]
Ok. Please try updating the repository. I've pushed a fix, probably.

**Comment by monybg** [comment]
I can confirm - the update fixed the problem. Thank you!

**Comment by brainfoolong** [comment]
Awesome. Thx for reporting.
